version: "3.0"
services:
  redis:
    image: redis:latest
    container_name: proj-cache
    ports:
      - "6379:6379"
  web:
    container_name: proj-application
    build:
      context: .
      dockerfile: .Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/pycon/
    ports:
      - "8000:8000"
    depends_on:
      - redis
